"""Governance domain enumerations for pharma AI agent orchestration."""

from enum import StrEnum


class DataClassification(StrEnum):
    PUBLIC = "PUBLIC"
    INTERNAL = "INTERNAL"
    CONFIDENTIAL = "CONFIDENTIAL"
    SENSITIVE = "SENSITIVE"
    RESTRICTED = "RESTRICTED"
    CRITICAL = "CRITICAL"


class AgentStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    SUSPENDED = "SUSPENDED"
    PENDING = "PENDING"


class GovernanceDecision(StrEnum):
    ALLOW = "ALLOW"
    ALLOW_WITH_RESTRICTIONS = "ALLOW_WITH_RESTRICTIONS"
    RESTRICT = "RESTRICT"  # alias for ALLOW_WITH_RESTRICTIONS
    REWRITE = "REWRITE"
    HUMAN_APPROVAL_REQUIRED = "HUMAN_APPROVAL_REQUIRED"
    HUMAN_APPROVAL = "HUMAN_APPROVAL_REQUIRED"  # alias
    BLOCK = "BLOCK"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class RequestType(StrEnum):
    TEXT = "TEXT"
    TOOL = "TOOL"
    COMPUTER = "COMPUTER"
    DATA = "DATA"
    AGENT = "AGENT"


class RewriteStatus(StrEnum):
    SAFE = "SAFE"
    REWRITTEN = "REWRITTEN"
    REVIEW = "REVIEW"
    BLOCKED = "BLOCKED"


class SensitiveDataAction(StrEnum):
    ALLOW = "ALLOW"
    REDACT = "REDACT"
    MASK = "MASK"
    GENERALIZE = "GENERALIZE"
    REWRITE = "REWRITE"
    REVIEW = "REVIEW"
    BLOCK = "BLOCK"


class ApprovalStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class SecurityEventSeverity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class SecurityEventCategory(StrEnum):
    UNAUTHORIZED_ACCESS = "UNAUTHORIZED_ACCESS"
    PERMISSION_VIOLATION = "PERMISSION_VIOLATION"
    RESTRICTED_DATA_ACCESS = "RESTRICTED_DATA_ACCESS"
    PRIVILEGE_ESCALATION = "PRIVILEGE_ESCALATION"
    TOOL_ABUSE = "TOOL_ABUSE"
    PROMPT_INJECTION = "PROMPT_INJECTION"
    POLICY_BYPASS = "POLICY_BYPASS"
    EXCESSIVE_TOOL_CALLS = "EXCESSIVE_TOOL_CALLS"
    UNUSUAL_BEHAVIOR = "UNUSUAL_BEHAVIOR"
    AUTH_FAILURE = "AUTH_FAILURE"
    AUTHZ_FAILURE = "AUTHZ_FAILURE"
    AUDIT_FAILURE = "AUDIT_FAILURE"
    APPROVAL_BYPASS = "APPROVAL_BYPASS"
    DARKWEB_ACCESS_ATTEMPT = "DARKWEB_ACCESS_ATTEMPT"
    DARKWEB_NAVIGATION_ATTEMPT = "DARKWEB_NAVIGATION_ATTEMPT"
    DARKWEB_SEARCH_ATTEMPT = "DARKWEB_SEARCH_ATTEMPT"
    DARKWEB_COMPUTER_USE_ATTEMPT = "DARKWEB_COMPUTER_USE_ATTEMPT"
    DARKWEB_TOOL_USE_ATTEMPT = "DARKWEB_TOOL_USE_ATTEMPT"
    NETWORK_CONTROL_BYPASS = "NETWORK_CONTROL_BYPASS"
    SECURITY_POLICY_BYPASS = "SECURITY_POLICY_BYPASS"
    DARKWEB_DATA_EXFILTRATION = "DARKWEB_DATA_EXFILTRATION"
    GUARDRAIL_BYPASS_ATTEMPT = "GUARDRAIL_BYPASS_ATTEMPT"
    IMAGE_PROMPT_INJECTION = "IMAGE_PROMPT_INJECTION"
    VISUAL_AUTHORITY_SPOOFING = "VISUAL_AUTHORITY_SPOOFING"
    PHI_EXPOSURE_ATTEMPT = "PHI_EXPOSURE_ATTEMPT"
    PII_EXPOSURE_ATTEMPT = "PII_EXPOSURE_ATTEMPT"
    SECRET_EXPOSURE = "SECRET_EXPOSURE"
    DATA_EXFILTRATION_ATTEMPT = "DATA_EXFILTRATION_ATTEMPT"
    MALICIOUS_URL = "MALICIOUS_URL"
    PHISHING_ATTEMPT = "PHISHING_ATTEMPT"
    MALWARE_EXECUTION_ATTEMPT = "MALWARE_EXECUTION_ATTEMPT"
    COMPUTER_USE_MANIPULATION = "COMPUTER_USE_MANIPULATION"
    NETWORK_BYPASS_ATTEMPT = "NETWORK_BYPASS_ATTEMPT"
    REGULATORY_MANIPULATION_ATTEMPT = "REGULATORY_MANIPULATION_ATTEMPT"
    CLINICAL_SAFETY_VIOLATION = "CLINICAL_SAFETY_VIOLATION"
    MANUFACTURING_SAFETY_VIOLATION = "MANUFACTURING_SAFETY_VIOLATION"


# --- Data permissions ---
class DataPermission(StrEnum):
    READ_LITERATURE = "READ_LITERATURE"
    READ_PATENTS = "READ_PATENTS"
    READ_INTERNAL_DOCUMENTS = "READ_INTERNAL_DOCUMENTS"
    READ_CLINICAL_DATA = "READ_CLINICAL_DATA"
    READ_PATIENT_DATA = "READ_PATIENT_DATA"
    READ_PV_DATA = "READ_PV_DATA"
    READ_MANUFACTURING_DATA = "READ_MANUFACTURING_DATA"
    READ_QMS_DATA = "READ_QMS_DATA"
    READ_REGULATORY_DATA = "READ_REGULATORY_DATA"
    READ_CRM_DATA = "READ_CRM_DATA"
    READ_GENOMIC_DATA = "READ_GENOMIC_DATA"
    READ_SCIENTIFIC_DATABASES = "READ_SCIENTIFIC_DATABASES"
    READ_INTERNAL_RESEARCH = "READ_INTERNAL_RESEARCH"
    READ_MOLECULAR_DATABASES = "READ_MOLECULAR_DATABASES"
    READ_COMPOUND_LIBRARIES = "READ_COMPOUND_LIBRARIES"
    READ_SAFETY_REPORTS = "READ_SAFETY_REPORTS"
    READ_SITE_PERFORMANCE = "READ_SITE_PERFORMANCE"
    READ_EDC = "READ_EDC"
    READ_CTMS = "READ_CTMS"
    READ_ERP = "READ_ERP"
    READ_MES = "READ_MES"
    READ_LIMS = "READ_LIMS"
    READ_SCADA = "READ_SCADA"
    READ_INVENTORY = "READ_INVENTORY"
    READ_SUPPLIER_DATA = "READ_SUPPLIER_DATA"
    READ_TEMPLATES = "READ_TEMPLATES"
    READ_CODING_DICTIONARIES = "READ_CODING_DICTIONARIES"


# --- Tool permissions ---
class ToolPermission(StrEnum):
    SEARCH_LITERATURE = "SEARCH_LITERATURE"
    SEARCH_PATENTS = "SEARCH_PATENTS"
    RUN_ANALYTICS = "RUN_ANALYTICS"
    RUN_ML_MODEL = "RUN_ML_MODEL"
    RUN_STATISTICAL_MODEL = "RUN_STATISTICAL_MODEL"
    RUN_SIMULATION = "RUN_SIMULATION"
    RUN_BIOINFORMATICS_PIPELINE = "RUN_BIOINFORMATICS_PIPELINE"
    RUN_COMPUTATIONAL_CHEMISTRY = "RUN_COMPUTATIONAL_CHEMISTRY"
    RUN_COMPUTATIONAL_SCREENING = "RUN_COMPUTATIONAL_SCREENING"
    RUN_ADMET_MODEL = "RUN_ADMET_MODEL"
    ACCESS_LIMS = "ACCESS_LIMS"
    ACCESS_EDC = "ACCESS_EDC"
    ACCESS_CTMS = "ACCESS_CTMS"
    ACCESS_QMS = "ACCESS_QMS"
    ACCESS_MES = "ACCESS_MES"
    ACCESS_ERP = "ACCESS_ERP"


# --- Action permissions ---
class ActionPermission(StrEnum):
    CREATE_DRAFT = "CREATE_DRAFT"
    CREATE_REPORT = "CREATE_REPORT"
    CREATE_ALERT = "CREATE_ALERT"
    CREATE_CASE = "CREATE_CASE"
    CREATE_QUERY = "CREATE_QUERY"
    CREATE_RECOMMENDATION = "CREATE_RECOMMENDATION"
    CREATE_SAFETY_CASE = "CREATE_SAFETY_CASE"
    CREATE_SAFETY_ALERT = "CREATE_SAFETY_ALERT"
    CREATE_SAFETY_FINDING = "CREATE_SAFETY_FINDING"
    CREATE_DATA_QUALITY_QUERY = "CREATE_DATA_QUALITY_QUERY"
    CREATE_CODING_RECOMMENDATION = "CREATE_CODING_RECOMMENDATION"
    CREATE_RECRUITMENT_CANDIDATE = "CREATE_RECRUITMENT_CANDIDATE"
    CREATE_ELIGIBILITY_ASSESSMENT = "CREATE_ELIGIBILITY_ASSESSMENT"
    CREATE_ANALYSIS_OUTPUT = "CREATE_ANALYSIS_OUTPUT"
    WRITE_CANDIDATE_DESIGNS = "WRITE_CANDIDATE_DESIGNS"
    WRITE_SCREENING_RESULTS = "WRITE_SCREENING_RESULTS"
    WRITE_PREDICTIONS = "WRITE_PREDICTIONS"
    WRITE_ANALYSIS_RESULTS = "WRITE_ANALYSIS_RESULTS"
    EDIT_DOCUMENT = "EDIT_DOCUMENT"
    EDIT_RECORD = "EDIT_RECORD"
    UPDATE_CASE = "UPDATE_CASE"
    UPDATE_WORKFLOW = "UPDATE_WORKFLOW"


# --- Restricted actions (never implicitly granted) ---
class RestrictedAction(StrEnum):
    APPROVE = "APPROVE"
    PUBLISH = "PUBLISH"
    SUBMIT_TO_REGULATOR = "SUBMIT_TO_REGULATOR"
    RELEASE_BATCH = "RELEASE_BATCH"
    MODIFY_PATIENT_RECORD = "MODIFY_PATIENT_RECORD"
    CHANGE_PRODUCTION_PROCESS = "CHANGE_PRODUCTION_PROCESS"
    SEND_EXTERNAL_COMMUNICATION = "SEND_EXTERNAL_COMMUNICATION"
    DELETE_RECORD = "DELETE_RECORD"
    CHANGE_AGENT_PERMISSIONS = "CHANGE_AGENT_PERMISSIONS"
    CHANGE_SECURITY_POLICY = "CHANGE_SECURITY_POLICY"
    FINALIZE_CASE = "FINALIZE_CASE"
    FINALIZE_PROTOCOL = "FINALIZE_PROTOCOL"
    ENROLL_PATIENT = "ENROLL_PATIENT"
    ACTIVATE_TRIAL = "ACTIVATE_TRIAL"
    APPROVE_CAPA = "APPROVE_CAPA"
    APPROVE_DEVIATION = "APPROVE_DEVIATION"
    PUBLISH_SOP = "PUBLISH_SOP"
    CLOSE_QUALITY_EVENT = "CLOSE_QUALITY_EVENT"
    OVERRIDE_QUALITY_CONTROL = "OVERRIDE_QUALITY_CONTROL"
    LABEL_APPROVAL = "LABEL_APPROVAL"
    DISABLE_GOVERNANCE = "DISABLE_GOVERNANCE"
    DISABLE_LOGGING = "DISABLE_LOGGING"
    DELETE_AUDIT_RECORD = "DELETE_AUDIT_RECORD"
    CREATE_UNRESTRICTED_CREDENTIALS = "CREATE_UNRESTRICTED_CREDENTIALS"
    MODIFY_AGENT_REGISTRY = "MODIFY_AGENT_REGISTRY"
    MODIFY_ANOTHER_AGENT_PERMISSIONS = "MODIFY_ANOTHER_AGENT_PERMISSIONS"
    DISABLE_HUMAN_APPROVAL = "DISABLE_HUMAN_APPROVAL"
    EMERGENCY_STOP = "EMERGENCY_STOP"
    DIAGNOSE = "DIAGNOSE"
    PRESCRIBE = "PRESCRIBE"
    CHANGE_TREATMENT = "CHANGE_TREATMENT"
    MAKE_MEDICAL_DECISION = "MAKE_MEDICAL_DECISION"
    INITIATE_LAB_EXPERIMENT = "INITIATE_LAB_EXPERIMENT"
    MODIFY_SOURCE_DATABASE = "MODIFY_SOURCE_DATABASE"
    DELETE_RESEARCH_DATA = "DELETE_RESEARCH_DATA"
    SILENTLY_MODIFY_PATIENT_DATA = "SILENTLY_MODIFY_PATIENT_DATA"


# --- Computer-use permissions (granular, never bundled) ---
class ComputerPermission(StrEnum):
    COMPUTER_VIEW_SCREEN = "COMPUTER_VIEW_SCREEN"
    COMPUTER_CLICK = "COMPUTER_CLICK"
    COMPUTER_TYPE = "COMPUTER_TYPE"
    COMPUTER_SCROLL = "COMPUTER_SCROLL"
    COMPUTER_KEYBOARD = "COMPUTER_KEYBOARD"
    COMPUTER_MOUSE = "COMPUTER_MOUSE"
    COMPUTER_OPEN_APPLICATION = "COMPUTER_OPEN_APPLICATION"
    COMPUTER_READ_FILE = "COMPUTER_READ_FILE"
    COMPUTER_WRITE_FILE = "COMPUTER_WRITE_FILE"
    COMPUTER_UPLOAD_FILE = "COMPUTER_UPLOAD_FILE"
    COMPUTER_DOWNLOAD_FILE = "COMPUTER_DOWNLOAD_FILE"
    COMPUTER_BROWSER_NAVIGATION = "COMPUTER_BROWSER_NAVIGATION"
    COMPUTER_EXECUTE_COMMAND = "COMPUTER_EXECUTE_COMMAND"
    COMPUTER_INSTALL_SOFTWARE = "COMPUTER_INSTALL_SOFTWARE"
    COMPUTER_SEND_MESSAGE = "COMPUTER_SEND_MESSAGE"
    COMPUTER_SEND_EMAIL = "COMPUTER_SEND_EMAIL"
    COMPUTER_SUBMIT_FORM = "COMPUTER_SUBMIT_FORM"


# --- External communication permissions ---
class ExternalPermission(StrEnum):
    SEND_EMAIL = "SEND_EMAIL"
    SEND_MESSAGE = "SEND_MESSAGE"
    EXTERNAL_API_CALL = "EXTERNAL_API_CALL"
    EXTERNAL_FILE_UPLOAD = "EXTERNAL_FILE_UPLOAD"


# --- General data read levels ---
class DataReadLevel(StrEnum):
    READ_PUBLIC = "READ_PUBLIC"
    READ_INTERNAL = "READ_INTERNAL"
    READ_CONFIDENTIAL = "READ_CONFIDENTIAL"
    READ_SENSITIVE = "READ_SENSITIVE"
    READ_RESTRICTED = "READ_RESTRICTED"
    READ_CRITICAL = "READ_CRITICAL"
